### ISSUE TITLE
Select sem usar o react-select 

### ISSUE THREAD

**Issue by diegofullstackjs** [unform/unform#345]
Como posso fazer a validação se o usuario selecionou uma opçao do option?
eu vi que so tem exemplo utilizando o react-select, e eu particularmente nao quero utilizar, entao como seria utilizando option normal ?

**Comment by carlosallexandre** [comment]
Hey @diegofullstackjs,

[Sandbox: unform-select](https://codesandbox.io/s/unform-select-vki6r?file=/src/App.tsx)

Tell me if it is whaty you looking for.

**Comment by jpedroschmitz** [comment]
Hey @diegofullstackjs, I am going to close this issue because it is not following the guidelines [described here](https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.

I recommend you open a new issue in English.
